/* eslint-disable import/no-anonymous-default-export */
export default {
	login: "ibktommy",
	id: 79788174,
	node_id: "MDQ6VXNlcjc5Nzg4MTc0",
	avatar_url: "https://avatars.githubusercontent.com/u/79788174?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/ibktommy",
	html_url: "https://github.com/ibktommy",
	followers_url: "https://api.github.com/users/ibktommy/followers",
	following_url: "https://api.github.com/users/ibktommy/following{/other_user}",
	gists_url: "https://api.github.com/users/ibktommy/gists{/gist_id}",
	starred_url: "https://api.github.com/users/ibktommy/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/ibktommy/subscriptions",
	organizations_url: "https://api.github.com/users/ibktommy/orgs",
	repos_url: "https://api.github.com/users/ibktommy/repos",
	events_url: "https://api.github.com/users/ibktommy/events{/privacy}",
	received_events_url: "https://api.github.com/users/ibktommy/received_events",
	type: "User",
	site_admin: false,
	name: "Anjorin Tomide Abdulquadri",
	company: null,
	blog: "https://atomdev-portfolio.netlify.app/",
	location: "NIGERIA",
	email: null,
	hireable: true,
	bio: "I am a passionate computer programmer. Currently a Frontend Developer and progressing to become a Fullstack Developer with UI/UX professional skills.",
	twitter_username: "ATOMQuadri",
	public_repos: 48,
	public_gists: 0,
	followers: 14,
	following: 17,
	created_at: "2021-02-28T10:05:38Z",
	updated_at: "2022-08-17T12:20:30Z",
}