// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    login: "mamba-dev-KE",
    id: 10088485,
    node_id: "MDQ6VXNlcjEwMDg4NDg1",
    avatar_url: "https://avatars.githubusercontent.com/u/10088485?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mamba-dev-KE",
    html_url: "https://github.com/mamba-dev-KE",
    followers_url: "https://api.github.com/users/mamba-dev-KE/followers",
    following_url: "https://api.github.com/users/mamba-dev-KE/following{/other_user}",
    gists_url: "https://api.github.com/users/mamba-dev-KE/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mamba-dev-KE/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mamba-dev-KE/subscriptions",
    organizations_url: "https://api.github.com/users/mamba-dev-KE/orgs",
    repos_url: "https://api.github.com/users/mamba-dev-KE/repos",
    events_url: "https://api.github.com/users/mamba-dev-KE/events{/privacy}",
    received_events_url: "https://api.github.com/users/mamba-dev-KE/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "fluxstride",
    id: 65285073,
    node_id: "MDQ6VXNlcjY1Mjg1MDcz",
    avatar_url: "https://avatars.githubusercontent.com/u/65285073?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/fluxstride",
    html_url: "https://github.com/fluxstride",
    followers_url: "https://api.github.com/users/fluxstride/followers",
    following_url: "https://api.github.com/users/fluxstride/following{/other_user}",
    gists_url: "https://api.github.com/users/fluxstride/gists{/gist_id}",
    starred_url: "https://api.github.com/users/fluxstride/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/fluxstride/subscriptions",
    organizations_url: "https://api.github.com/users/fluxstride/orgs",
    repos_url: "https://api.github.com/users/fluxstride/repos",
    events_url: "https://api.github.com/users/fluxstride/events{/privacy}",
    received_events_url: "https://api.github.com/users/fluxstride/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "smilingprogrammer",
    id: 66224527,
    node_id: "MDQ6VXNlcjY2MjI0NTI3",
    avatar_url: "https://avatars.githubusercontent.com/u/66224527?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/smilingprogrammer",
    html_url: "https://github.com/smilingprogrammer",
    followers_url: "https://api.github.com/users/smilingprogrammer/followers",
    following_url: "https://api.github.com/users/smilingprogrammer/following{/other_user}",
    gists_url: "https://api.github.com/users/smilingprogrammer/gists{/gist_id}",
    starred_url: "https://api.github.com/users/smilingprogrammer/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/smilingprogrammer/subscriptions",
    organizations_url: "https://api.github.com/users/smilingprogrammer/orgs",
    repos_url: "https://api.github.com/users/smilingprogrammer/repos",
    events_url: "https://api.github.com/users/smilingprogrammer/events{/privacy}",
    received_events_url: "https://api.github.com/users/smilingprogrammer/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "40N30E722296800Z",
    id: 70603990,
    node_id: "MDQ6VXNlcjcwNjAzOTkw",
    avatar_url: "https://avatars.githubusercontent.com/u/70603990?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/40N30E722296800Z",
    html_url: "https://github.com/40N30E722296800Z",
    followers_url: "https://api.github.com/users/40N30E722296800Z/followers",
    following_url: "https://api.github.com/users/40N30E722296800Z/following{/other_user}",
    gists_url: "https://api.github.com/users/40N30E722296800Z/gists{/gist_id}",
    starred_url: "https://api.github.com/users/40N30E722296800Z/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/40N30E722296800Z/subscriptions",
    organizations_url: "https://api.github.com/users/40N30E722296800Z/orgs",
    repos_url: "https://api.github.com/users/40N30E722296800Z/repos",
    events_url: "https://api.github.com/users/40N30E722296800Z/events{/privacy}",
    received_events_url: "https://api.github.com/users/40N30E722296800Z/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Wael2001-png",
    id: 71949263,
    node_id: "MDQ6VXNlcjcxOTQ5MjYz",
    avatar_url: "https://avatars.githubusercontent.com/u/71949263?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Wael2001-png",
    html_url: "https://github.com/Wael2001-png",
    followers_url: "https://api.github.com/users/Wael2001-png/followers",
    following_url: "https://api.github.com/users/Wael2001-png/following{/other_user}",
    gists_url: "https://api.github.com/users/Wael2001-png/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Wael2001-png/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Wael2001-png/subscriptions",
    organizations_url: "https://api.github.com/users/Wael2001-png/orgs",
    repos_url: "https://api.github.com/users/Wael2001-png/repos",
    events_url: "https://api.github.com/users/Wael2001-png/events{/privacy}",
    received_events_url: "https://api.github.com/users/Wael2001-png/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gurr-i",
    id: 73361014,
    node_id: "MDQ6VXNlcjczMzYxMDE0",
    avatar_url: "https://avatars.githubusercontent.com/u/73361014?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gurr-i",
    html_url: "https://github.com/gurr-i",
    followers_url: "https://api.github.com/users/gurr-i/followers",
    following_url: "https://api.github.com/users/gurr-i/following{/other_user}",
    gists_url: "https://api.github.com/users/gurr-i/gists{/gist_id}",
    starred_url: "https://api.github.com/users/gurr-i/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gurr-i/subscriptions",
    organizations_url: "https://api.github.com/users/gurr-i/orgs",
    repos_url: "https://api.github.com/users/gurr-i/repos",
    events_url: "https://api.github.com/users/gurr-i/events{/privacy}",
    received_events_url: "https://api.github.com/users/gurr-i/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Cheeh1",
    id: 87880831,
    node_id: "MDQ6VXNlcjg3ODgwODMx",
    avatar_url: "https://avatars.githubusercontent.com/u/87880831?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Cheeh1",
    html_url: "https://github.com/Cheeh1",
    followers_url: "https://api.github.com/users/Cheeh1/followers",
    following_url: "https://api.github.com/users/Cheeh1/following{/other_user}",
    gists_url: "https://api.github.com/users/Cheeh1/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Cheeh1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Cheeh1/subscriptions",
    organizations_url: "https://api.github.com/users/Cheeh1/orgs",
    repos_url: "https://api.github.com/users/Cheeh1/repos",
    events_url: "https://api.github.com/users/Cheeh1/events{/privacy}",
    received_events_url: "https://api.github.com/users/Cheeh1/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "zeespacehub",
    id: 87985617,
    node_id: "MDQ6VXNlcjg3OTg1NjE3",
    avatar_url: "https://avatars.githubusercontent.com/u/87985617?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/zeespacehub",
    html_url: "https://github.com/zeespacehub",
    followers_url: "https://api.github.com/users/zeespacehub/followers",
    following_url: "https://api.github.com/users/zeespacehub/following{/other_user}",
    gists_url: "https://api.github.com/users/zeespacehub/gists{/gist_id}",
    starred_url: "https://api.github.com/users/zeespacehub/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/zeespacehub/subscriptions",
    organizations_url: "https://api.github.com/users/zeespacehub/orgs",
    repos_url: "https://api.github.com/users/zeespacehub/repos",
    events_url: "https://api.github.com/users/zeespacehub/events{/privacy}",
    received_events_url: "https://api.github.com/users/zeespacehub/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ohm26",
    id: 88041757,
    node_id: "MDQ6VXNlcjg4MDQxNzU3",
    avatar_url: "https://avatars.githubusercontent.com/u/88041757?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ohm26",
    html_url: "https://github.com/ohm26",
    followers_url: "https://api.github.com/users/ohm26/followers",
    following_url: "https://api.github.com/users/ohm26/following{/other_user}",
    gists_url: "https://api.github.com/users/ohm26/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ohm26/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ohm26/subscriptions",
    organizations_url: "https://api.github.com/users/ohm26/orgs",
    repos_url: "https://api.github.com/users/ohm26/repos",
    events_url: "https://api.github.com/users/ohm26/events{/privacy}",
    received_events_url: "https://api.github.com/users/ohm26/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "pusetsom",
    id: 92914430,
    node_id: "U_kgDOBYnC_g",
    avatar_url: "https://avatars.githubusercontent.com/u/92914430?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/pusetsom",
    html_url: "https://github.com/pusetsom",
    followers_url: "https://api.github.com/users/pusetsom/followers",
    following_url: "https://api.github.com/users/pusetsom/following{/other_user}",
    gists_url: "https://api.github.com/users/pusetsom/gists{/gist_id}",
    starred_url: "https://api.github.com/users/pusetsom/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/pusetsom/subscriptions",
    organizations_url: "https://api.github.com/users/pusetsom/orgs",
    repos_url: "https://api.github.com/users/pusetsom/repos",
    events_url: "https://api.github.com/users/pusetsom/events{/privacy}",
    received_events_url: "https://api.github.com/users/pusetsom/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Chiemerie11",
    id: 96776816,
    node_id: "U_kgDOBcSycA",
    avatar_url: "https://avatars.githubusercontent.com/u/96776816?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Chiemerie11",
    html_url: "https://github.com/Chiemerie11",
    followers_url: "https://api.github.com/users/Chiemerie11/followers",
    following_url: "https://api.github.com/users/Chiemerie11/following{/other_user}",
    gists_url: "https://api.github.com/users/Chiemerie11/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Chiemerie11/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Chiemerie11/subscriptions",
    organizations_url: "https://api.github.com/users/Chiemerie11/orgs",
    repos_url: "https://api.github.com/users/Chiemerie11/repos",
    events_url: "https://api.github.com/users/Chiemerie11/events{/privacy}",
    received_events_url: "https://api.github.com/users/Chiemerie11/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "capitolcomputers",
    id: 99561454,
    node_id: "U_kgDOBe8v7g",
    avatar_url: "https://avatars.githubusercontent.com/u/99561454?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/capitolcomputers",
    html_url: "https://github.com/capitolcomputers",
    followers_url: "https://api.github.com/users/capitolcomputers/followers",
    following_url: "https://api.github.com/users/capitolcomputers/following{/other_user}",
    gists_url: "https://api.github.com/users/capitolcomputers/gists{/gist_id}",
    starred_url: "https://api.github.com/users/capitolcomputers/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/capitolcomputers/subscriptions",
    organizations_url: "https://api.github.com/users/capitolcomputers/orgs",
    repos_url: "https://api.github.com/users/capitolcomputers/repos",
    events_url: "https://api.github.com/users/capitolcomputers/events{/privacy}",
    received_events_url: "https://api.github.com/users/capitolcomputers/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Skhalil772",
    id: 100126073,
    node_id: "U_kgDOBffNeQ",
    avatar_url: "https://avatars.githubusercontent.com/u/100126073?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Skhalil772",
    html_url: "https://github.com/Skhalil772",
    followers_url: "https://api.github.com/users/Skhalil772/followers",
    following_url: "https://api.github.com/users/Skhalil772/following{/other_user}",
    gists_url: "https://api.github.com/users/Skhalil772/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Skhalil772/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Skhalil772/subscriptions",
    organizations_url: "https://api.github.com/users/Skhalil772/orgs",
    repos_url: "https://api.github.com/users/Skhalil772/repos",
    events_url: "https://api.github.com/users/Skhalil772/events{/privacy}",
    received_events_url: "https://api.github.com/users/Skhalil772/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Nneji123",
    id: 101701760,
    node_id: "U_kgDOBg_YgA",
    avatar_url: "https://avatars.githubusercontent.com/u/101701760?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Nneji123",
    html_url: "https://github.com/Nneji123",
    followers_url: "https://api.github.com/users/Nneji123/followers",
    following_url: "https://api.github.com/users/Nneji123/following{/other_user}",
    gists_url: "https://api.github.com/users/Nneji123/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Nneji123/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Nneji123/subscriptions",
    organizations_url: "https://api.github.com/users/Nneji123/orgs",
    repos_url: "https://api.github.com/users/Nneji123/repos",
    events_url: "https://api.github.com/users/Nneji123/events{/privacy}",
    received_events_url: "https://api.github.com/users/Nneji123/received_events",
    type: "User",
    site_admin: false,
  },
]